CREATE DATABASE JOSE_TESTES
  WITH OWNER = postgres
       ENCODING = 'UTF8'
       LC_COLLATE = 'en_US.UTF-8'
       LC_CTYPE = 'en_US.UTF-8'
       TABLESPACE = pg_default
       CONNECTION LIMIT = -1;




DROP TABLE IF EXISTS assistants CASCADE;   
DROP TABLE IF EXISTS assistants_files CASCADE;  
DROP TABLE IF EXISTS assistants_instructions CASCADE;  
DROP TABLE IF EXISTS assistants_messages CASCADE;  
DROP TABLE IF EXISTS assistants_threads CASCADE;  
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS THREADS CASCADE;
